default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: vue_ex
  password: vue_ex
  host: localhost
  port: 5432

development:
  <<: *default
  database: vue_ex_dev
test:
  <<: *default
  database: vue_ex_test

production:
  <<: *default
  database: vue_ex_prod